version: '3'

services:
  servidorweb2:
    #image: webdevops/php-apache
    build: .
    container_name: servidorweb2
    volumes:
      - ./app:/var/www/html
      #- ./app:/app
      
    ports:
      - 81:80
